mink:
    base_url:   http://localhost/app_dev.php
    show_cmd:   mate %%s


    default_session: goutte            # use for real HTTP test (remote server)

    goutte:
        server_parameters:
            host: http://localhost
    sahi:
        host:     x.local

behat: ~