sonata_media:
    db_driver:       doctrine_orm # | doctrine_mongodb
    default_context: default
    contexts:
        default:  # the default context is mandatory
            download:
                mode: http # X-Sendfile | http
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small:  { width: 100,  quality: 100  }
                sdtv:   { width: 480,  quality: 360  }
                edtv:   { width: 720,  quality: 480  }
                hdtv:   { width: 1280, quality: 720  }
                hd:     { width: 1920, quality: 1080 }

        news:
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small:  { width: 100,  quality: 100  }
                sdtv:   { width: 480,  quality: 360  }
                edtv:   { width: 720,  quality: 480  }
                hdtv:   { width: 1280, quality: 720  }
                hd:     { width: 1920, quality: 1080 }

    cdn:
        # define the public base url for the uploaded media
        server:
            path:      %sonata_media.cdn.host%

    filesystem:
        # define where the uploaded file will be stored
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     true

    providers:
        file:
            resizer:    false

    pixlr:
        enabled:  true
        referrer: Victor Hugo Valle Website

    resizer:
        simple:
            mode:  inset

# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationSonataMediaBundle: ~
                    SonataMediaBundle: ~